[package]
name = "cmem-eval-continuity"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
cmem-eval = { path = "../cmem-eval" }

[dev-dependencies]
tokio.workspace = true
uuid.workspace = true

tempfile = "3"
